### ISSUE TITLE
GO identifiers.org URIs are double-encoded

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/RDF-platform#3] opened 2017-10-30 21:49 UTC
E.g

`curl -H 'Accept: text/turtle' -L http://rdf.ebi.ac.uk/resource/ensembl.transcript/ENST00000265620`

yields triples like:

```
       <http://rdf.ebi.ac.uk/terms/ensembl/DIRECT>
                <http://identifiers.org/go/GO%253A0007165> , <http://identifiers.org/go/GO%253A0004871> , <http://identifiers.org/go/GO%253A0016020> , <http://identifiers.org/go/GO%253A0060789> , <http://identifiers.org/go/GO%253A0005737> , <http://identifiers.org/go/GO%253A0005829> , <http://identifiers.org/go/GO%253A0070527> , <http://identifiers.org/go/GO%253A0003924> , <http://identifiers.org/go/GO%253A0050890> , <http://identifiers.org/go/GO%253A0007608> , <http://identifiers.org/go/GO%253A0007189> , <http://identifiers.org/go/GO%253A0060348> , <http://identifiers.org/refseq/XM_017027819> , <http://identifiers.org/go/GO%253A0050796> , <http://identifiers.org/go/GO%253A0007191> , <http://identifiers.org/go/GO%253A0005886> , <http://identifiers.org/refseq/XM_017027815> , <http://identifiers.org/go/GO%253A0046907> , <http://identifiers.org/go/GO%253A0070062> , <http://identifiers.org/go/GO%253A0007186> , <http://identifiers.org/go/GO%253A0071377> , <http://identifiers.org/go/GO%253A0031683> , <http://identifiers.org/go/GO%253A0003091> , <http://identifiers.org/go/GO%253A0071380> , <http://identifiers.org/ccds/CCDS42892> , <http://identifiers.org/go/GO%253A0043950> , <http://identifiers.org/refseq/XM_017027818> , <http://identifiers.org/go/GO%253A0032588> , <http://identifiers.org/go/GO%253A0007190> , <http://identifiers.org/go/GO%253A0005515> , <http://identifiers.org/go/GO%253A0046872> , <http://identifiers.org/go/GO%253A0005525> , <http://identifiers.org/go/GO%253A0048589> , <http://identifiers.org/go/GO%253A0019001> , <http://identifiers.org/go/GO%253A0005834> , <http://identifiers.org/go/GO%253A0071880> , <http://identifiers.org/refseq/XM_017027817> , <http://identifiers.org/go/GO%253A0031224> , <http://identifiers.org/refseq/NM_001077489> , <http://identifiers.org/go/GO%253A0043547> , <http://identifiers.org/refseq/XM_017027816> , <http://identifiers.org/go/GO%253A0000166> , <http://identifiers.org/refseq/XM_017027820> , <http://identifiers.org/go/GO%253A0030819> , <http://identifiers.org/go/GO%253A0071870> ;
```

the GO IDs are double encoded. http://identifiers.org/go/GO%253A0071870 gives a 404 on identifiers.org

```
>>> from urllib.parse import unquote
>>> unquote("http://identifiers.org/go/GO%253A0071870")
'http://identifiers.org/go/GO%3A0071870'
>>> unquote(unquote("http://identifiers.org/go/GO%253A0071870"))
'http://identifiers.org/go/GO:0071870'
```

Consider also using OBO PURLs for GO

**Comment by avullo** [comment] 2017-10-31 09:19
This has already been addressed, but it was after the dumps for release 90 were produced back in August. The correct unescaped identifiers will be available in release 91 (Dec 2017).

See https://github.com/Ensembl/ensembl-io/commit/517aa5c89b478702108c03699784aa1ac206c5f3

**Comment by avullo** [comment] 2017-10-31 09:21
Same for the OBO PURLs for GO:

https://github.com/Ensembl/ensembl-io/commit/3286b138e92dfe7a897472196e399fc2aa66cc76#diff-10527bf5e3378c78b1a6d5d0ef280e89R137

**Comment by LLTommy** [comment] 2017-10-31 09:23
Hey Chris, thanks for reporting! As avullo just replied, we are aware of the problem and a fix is in place, but it will go into effect with the new ensembl rdf release! Please keep reporting if you find something suspicious! 

Cheers!

**Comment by LLTommy** [comment] 2017-11-08 14:25
I close this ticket for now, if the problem is still there after the new ensembl rdf release, please re-open!

**Closed by LLTommy** 2017-11-08 14:25 UTC
